### ISSUE TITLE
[feature] Application Logs

### ISSUE THREAD

**Issue by ijpatricio** [easypanel-io/community#19]
So, not only service logs, but also a pane for browsing log files.
Example, Laravel has the `storage/logs` folder.
We could list the several files in there, and see them in the browser. If they get too big, then they would have to be downloaded.
We could delete logs.

We could receive notifications (premium), when log files getting too big.
Also, notifications when disk size is getting too big. (cron task)

![image](https://user-images.githubusercontent.com/26031459/164837603-3d016452-d01c-4a48-8c68-cb630a5ddc01.png)

**Comment by deiucanta** [comment]
I'm hesitant to add this since each framework has different ways of storing logs. Also, if you have multiple replicas, it will be even harder to collect the logs. 

I think it's better to use something like Sentry if you want centralized logs - which you already mentioned in Discord.

Or, you could redirect the logs to stdout and they will be visible in the main "Logs" of the service. You can try `syslog` or `errorlog` channels. https://laravel.com/docs/9.x/logging#available-channel-drivers 

I will close this for now as I don't see a clear path to implementation.

**Comment by ijpatricio** [comment]
Yeah, this is where the self hosted Sentry comes in, as it has the adapters for a huge amount of frameworks
