### ISSUE TITLE
Traefik config

### ISSUE THREAD

**Issue by abdallahhkaram** [easypanel-io/community#42]
Add ability to config traefik

**Comment by deiucanta** [comment]
You can find the Traefik config in `/etc/easypanel/traefik/config.json`. However, it's not safe to change it because the panel might override it in a future release.

If you want to disable Traefik's Dashboard, as you mentioned on the Discord channel, I pushed a fix for it. Pull the latest release of Easypanel and then run the setup script again (you will not lose any of your data).

```bash
docker image pull easypanel/easypanel

docker run --rm -it \
  -v /etc/easypanel:/etc/easypanel \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  easypanel/easypanel setup
```
